version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    labels: ["dependencies"]
    schedule:
      interval: "weekly"
      day: "saturday"
  - package-ecosystem: "gomod"
    directory: "/"
    labels: ["dependencies"]
    schedule:
      interval: "weekly"
      day: "saturday"
