name: test
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: 1.23.3
      - uses: actions/checkout@v4
      - name: Test (race)
        run: go test ./... -race
      - name: Test (coverage)
        run: go test ./... -coverprofile=coverage.txt -covermode=atomic
      - name: Codecov
        uses: codecov/codecov-action@v5.5.0
        with:
          files: ./coverage.txt
          token: ${{ secrets.CODECOV_TOKEN }}
          
