name: test
on:
  pull_request:
    paths-ignore:
      - '*.md'
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Test (race)
        run: go test -mod vendor ./... -race
      - name: Test (coverage)
        run: go test -mod vendor ./... -coverprofile=coverage.txt -covermode=atomic
      - name: Codecov
        uses: codecov/codecov-action@v2.1.0
        with:
          files: ./coverage.txt
